version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.8.1
    - 1.9.0
  - dependency-name: docker-api
    versions:
    - 2.0.0
  - dependency-name: rubocop-rspec
    versions:
    - 1.41.0
